// context/mockData/courses.js
// Mock data for courses, assignments, and gradebook

// ============================================================================
// COURSES
// ============================================================================

export const MOCK_INSTRUCTOR_COURSES = [
  {
    id: "1",
    name: "PHILO/MATH/CSCI 275 - Spring 2025",
    code: "PHIL275-01",
    semester: "Spring 2025",
    status: "current",
    studentCount: 30,
    color: "#1976d2",
    latePolicy: {
      enabled: true,
      maxDaysLate: 7,
      penaltyPerDay: 10,
    },
    gradingScale: [
      { letter: "A", minPercent: 90, maxPercent: 100, color: "#10b981" },
      { letter: "B", minPercent: 80, maxPercent: 89, color: "#3b82f6" },
      { letter: "C", minPercent: 70, maxPercent: 79, color: "#f59e0b" },
      { letter: "D", minPercent: 60, maxPercent: 69, color: "#f97316" },
      { letter: "F", minPercent: 0, maxPercent: 59, color: "#ef4444" },
    ],
  },

  {
    id: "2",
    name: "Computer Science 101 - Spring 2025",
    code: "CS101-02",
    semester: "Spring 2025",
    status: "current",
    studentCount: 25,
    color: "#9c27b0",
    latePolicy: {
      enabled: true,
      maxDaysLate: 5,
      penaltyPerDay: 15,
    },
    gradingScale: [
      { letter: "A", minPercent: 93, maxPercent: 100, color: "#10b981" },
      { letter: "B", minPercent: 85, maxPercent: 92, color: "#3b82f6" },
      { letter: "C", minPercent: 75, maxPercent: 84, color: "#f59e0b" },
      { letter: "D", minPercent: 65, maxPercent: 74, color: "#f97316" },
      { letter: "F", minPercent: 0, maxPercent: 64, color: "#ef4444" },
    ],
  },

  {
    id: "3",
    name: "Data Structures - Fall 2024",
    code: "CS201-01",
    semester: "Fall 2024",
    status: "past",
    studentCount: 28,
    color: "#f57c00",
    latePolicy: {
      enabled: false,
      maxDaysLate: 0,
      penaltyPerDay: 0,
    },
    gradingScale: [
      { letter: "A", minPercent: 90, maxPercent: 100, color: "#22c55e" },
      { letter: "B", minPercent: 82, maxPercent: 89, color: "#6366f1" },
      { letter: "C", minPercent: 74, maxPercent: 81, color: "#f59e0b" },
      { letter: "D", minPercent: 65, maxPercent: 73, color: "#fb923c" },
      { letter: "F", minPercent: 0, maxPercent: 64, color: "#ef4444" },
    ],
  },
];

// ============================================================================
// ASSIGNMENTS
// ============================================================================

export const MOCK_ASSIGNMENTS_BY_COURSE = {
  1: [
    {
      id: "a1",
      courseId: "1",
      name: "Assignment 1",
      publishDate: "2026-01-08",
      publishTime: "00:00",
      dueDate: "2026-01-15",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 28,
      lateSubmissions: 3,
    },
    {
      id: "a2",
      courseId: "1",
      name: "Assignment 2",
      publishDate: "2026-01-15",
      publishTime: "00:00",
      dueDate: "2026-01-22",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 29,
      lateSubmissions: 5,
    },
    {
      id: "a3",
      courseId: "1",
      name: "Assignment 3",
      publishDate: "2026-01-22",
      publishTime: "00:00",
      dueDate: "2026-01-29",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 27,
      lateSubmissions: 2,
    },
    {
      id: "a4",
      courseId: "1",
      name: "Assignment 4",
      publishDate: "2026-01-29",
      publishTime: "00:00",
      dueDate: "2026-02-05",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 30,
      lateSubmissions: 7,
    },
    {
      id: "a5",
      courseId: "1",
      name: "Assignment 5",
      publishDate: "2026-02-05",
      publishTime: "00:00",
      dueDate: "2026-02-12",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 26,
      lateSubmissions: 4,
    },
    {
      id: "a6",
      courseId: "1",
      name: "Assignment 6",
      publishDate: "2026-02-12",
      publishTime: "00:00",
      dueDate: "2026-02-19",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 28,
      lateSubmissions: 1,
    },
    {
      id: "a7",
      courseId: "1",
      name: "Assignment 7",
      publishDate: "2026-02-19",
      publishTime: "00:00",
      dueDate: "2026-02-26",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 29,
      lateSubmissions: 3,
    },
    {
      id: "a8",
      courseId: "1",
      name: "Assignment 8",
      publishDate: "2026-02-26",
      publishTime: "00:00",
      dueDate: "2026-03-05",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 28,
      lateSubmissions: 2,
    },
    {
      id: "a9",
      courseId: "1",
      name: "Assignment 9",
      publishDate: "2026-03-05",
      publishTime: "00:00",
      dueDate: "2026-03-12",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 30,
      lateSubmissions: 4,
    },
    {
      id: "a10",
      courseId: "1",
      name: "Assignment 10",
      publishDate: "2026-03-12",
      publishTime: "00:00",
      dueDate: "2026-03-19",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 27,
      lateSubmissions: 1,
    },
    {
      id: "a11",
      courseId: "1",
      name: "Assignment 11",
      publishDate: "2026-03-19",
      publishTime: "00:00",
      dueDate: "2026-03-26",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 29,
      lateSubmissions: 5,
    },
    {
      id: "a12",
      courseId: "1",
      name: "Assignment 12",
      publishDate: "2026-03-26",
      publishTime: "00:00",
      dueDate: "2026-04-02",
      dueTime: "23:59",
      isPublished: false,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 30,
      submissions: 28,
      lateSubmissions: 2,
    },
  ],

  2: [
    {
      id: "a13",
      courseId: "2",
      name: "Homework 1",
      publishDate: "2026-01-13",
      publishTime: "00:00",
      dueDate: "2026-01-20",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 25,
      submissions: 24,
      lateSubmissions: 2,
    },
    {
      id: "a14",
      courseId: "2",
      name: "Homework 2",
      publishDate: "2026-01-20",
      publishTime: "00:00",
      dueDate: "2026-01-27",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      totalPoints: 100,
      totalStudents: 25,
      submissions: 23,
      lateSubmissions: 3,
    },
    {
      id: "a15",
      courseId: "2",
      name: "Midterm Project",
      publishDate: "2026-02-03",
      publishTime: "00:00",
      dueDate: "2026-02-10",
      dueTime: "23:59",
      isPublished: false,
      isLocked: false,
      totalPoints: 200,
      totalStudents: 25,
      submissions: 0,
      lateSubmissions: 0,
    },
  ],

  3: [
    {
      id: "a16",
      courseId: "3",
      name: "Project 1",
      publishDate: "2024-10-01",
      publishTime: "00:00",
      dueDate: "2024-10-15",
      dueTime: "23:59",
      isPublished: true,
      isLocked: true,
      totalPoints: 150,
      totalStudents: 28,
      submissions: 28,
      lateSubmissions: 0,
    },
    {
      id: "a17",
      courseId: "3",
      name: "Final Exam",
      publishDate: "2024-12-01",
      publishTime: "00:00",
      dueDate: "2024-12-15",
      dueTime: "23:59",
      isPublished: true,
      isLocked: true,
      totalPoints: 200,
      totalStudents: 28,
      submissions: 28,
      lateSubmissions: 1,
    },
  ],
};

// ============================================================================
// GRADEBOOK - Course 1 Students
// ============================================================================

export const MOCK_GRADEBOOK_BY_COURSE = {
  1: [
    {
      id: "s1",
      courseId: "1",
      studentId: "student_1",
      name: "Alice Johnson",
      email: "alice.j@university.edu",
      grades: {
        a1: 90,
        a2: 85,
        a3: 92,
        a4: 87,
        a5: 84,
        a6: 90,
        a7: 88,
        a8: 91,
        a9: 89,
        a10: 93,
        a11: 87,
        a12: 90,
      },
    },
    {
      id: "s2",
      courseId: "1",
      studentId: "student_2",
      name: "Bob Smith",
      email: "bob.s@university.edu",
      grades: {
        a1: 70,
        a2: 68,
        a3: 75,
        a4: 80,
        a5: 77,
        a6: 72,
        a7: 74,
        a8: 78,
        a9: 73,
        a10: 76,
        a11: 79,
        a12: 75,
      },
    },
    {
      id: "s3",
      courseId: "1",
      studentId: "student_3",
      name: "Carla Martinez",
      email: "carla.m@university.edu",
      grades: {
        a1: 95,
        a2: 93,
        a3: 96,
        a4: 94,
        a5: 91,
        a6: 97,
        a7: 95,
        a8: 96,
        a9: 94,
        a10: 98,
        a11: 93,
        a12: 97,
      },
    },
    {
      id: "s4",
      courseId: "1",
      studentId: "student_4",
      name: "David Chen",
      email: "david.c@university.edu",
      grades: {
        a1: 82,
        a2: 85,
        a3: 88,
        a4: 84,
        a5: 86,
        a6: 83,
        a7: 87,
        a8: 85,
        a9: 86,
        a10: 89,
        a11: 84,
        a12: 88,
      },
    },
    {
      id: "s5",
      courseId: "1",
      studentId: "student_5",
      name: "Emma Wilson",
      email: "emma.w@university.edu",
      grades: {
        a1: 78,
        a2: 80,
        a3: 82,
        a4: 79,
        a5: 81,
        a6: 77,
        a7: 83,
        a8: 80,
        a9: 82,
        a10: 84,
        a11: 79,
        a12: 81,
      },
    },
    {
      id: "s6",
      courseId: "1",
      studentId: "student_6",
      name: "Frank Rodriguez",
      email: "frank.r@university.edu",
      grades: {
        a1: 91,
        a2: 89,
        a3: 92,
        a4: 90,
        a5: 88,
        a6: 93,
        a7: 91,
        a8: 90,
        a9: 92,
        a10: 94,
        a11: 89,
        a12: 91,
      },
    },
    {
      id: "s7",
      courseId: "1",
      studentId: "student_7",
      name: "Grace Lee",
      email: "grace.l@university.edu",
      grades: {
        a1: 65,
        a2: 68,
        a3: 70,
        a4: 67,
        a5: 72,
        a6: 69,
        a7: 71,
        a8: 73,
        a9: 70,
        a10: 74,
        a11: 68,
        a12: 72,
      },
    },
    {
      id: "s8",
      courseId: "1",
      studentId: "student_8",
      name: "Henry Taylor",
      email: "henry.t@university.edu",
      grades: {
        a1: 88,
        a2: 87,
        a3: 90,
        a4: 85,
        a5: 89,
        a6: 86,
        a7: 88,
        a8: 91,
        a9: 87,
        a10: 90,
        a11: 88,
        a12: 89,
      },
    },
    {
      id: "s9",
      courseId: "1",
      studentId: "student_9",
      name: "Isabel Garcia",
      email: "isabel.g@university.edu",
      grades: {
        a1: 76,
        a2: 78,
        a3: 80,
        a4: 77,
        a5: 79,
        a6: 75,
        a7: 81,
        a8: 79,
        a9: 78,
        a10: 82,
        a11: 77,
        a12: 80,
      },
    },
    {
      id: "s10",
      courseId: "1",
      studentId: "student_10",
      name: "Jack Anderson",
      email: "jack.a@university.edu",
      grades: {
        a1: 92,
        a2: 94,
        a3: 91,
        a4: 93,
        a5: 95,
        a6: 90,
        a7: 94,
        a8: 92,
        a9: 93,
        a10: 96,
        a11: 91,
        a12: 94,
      },
    },
    {
      id: "s11",
      courseId: "1",
      studentId: "student_11",
      name: "Kelly Brown",
      email: "kelly.b@university.edu",
      grades: {
        a1: 83,
        a2: 81,
        a3: 85,
        a4: 82,
        a5: 84,
        a6: 80,
        a7: 86,
        a8: 83,
        a9: 85,
        a10: 87,
        a11: 82,
        a12: 84,
      },
    },
    {
      id: "s12",
      courseId: "1",
      studentId: "student_12",
      name: "Liam Murphy",
      email: "liam.m@university.edu",
      grades: {
        a1: 58,
        a2: 62,
        a3: 65,
        a4: 60,
        a5: 64,
        a6: 59,
        a7: 66,
        a8: 63,
        a9: 61,
        a10: 67,
        a11: 62,
        a12: 64,
      },
    },
    {
      id: "s13",
      courseId: "1",
      studentId: "student_13",
      name: "Maya Patel",
      email: "maya.p@university.edu",
      grades: {
        a1: 89,
        a2: 91,
        a3: 88,
        a4: 90,
        a5: 92,
        a6: 87,
        a7: 91,
        a8: 89,
        a9: 90,
        a10: 93,
        a11: 88,
        a12: 91,
      },
    },
    {
      id: "s14",
      courseId: "1",
      studentId: "student_14",
      name: "Noah Kim",
      email: "noah.k@university.edu",
      grades: {
        a1: 74,
        a2: 76,
        a3: 78,
        a4: 75,
        a5: 77,
        a6: 73,
        a7: 79,
        a8: 76,
        a9: 78,
        a10: 80,
        a11: 75,
        a12: 77,
      },
    },
    {
      id: "s15",
      courseId: "1",
      studentId: "student_15",
      name: "Olivia White",
      email: "olivia.w@university.edu",
      grades: {
        a1: 96,
        a2: 95,
        a3: 97,
        a4: 94,
        a5: 96,
        a6: 98,
        a7: 95,
        a8: 97,
        a9: 96,
        a10: 99,
        a11: 94,
        a12: 97,
      },
    },
    {
      id: "s16",
      courseId: "1",
      studentId: "student_16",
      name: "Peter Jackson",
      email: "peter.j@university.edu",
      grades: {
        a1: 81,
        a2: 83,
        a3: 85,
        a4: 82,
        a5: 84,
        a6: 80,
        a7: 86,
        a8: 83,
        a9: 85,
        a10: 87,
        a11: 82,
        a12: 84,
      },
    },
    {
      id: "s17",
      courseId: "1",
      studentId: "student_17",
      name: "Quinn Davis",
      email: "quinn.d@university.edu",
      grades: {
        a1: 87,
        a2: 89,
        a3: 86,
        a4: 88,
        a5: 90,
        a6: 85,
        a7: 89,
        a8: 87,
        a9: 88,
        a10: 91,
        a11: 86,
        a12: 89,
      },
    },
    {
      id: "s18",
      courseId: "1",
      studentId: "student_18",
      name: "Rachel Green",
      email: "rachel.g@university.edu",
      grades: {
        a1: 72,
        a2: 74,
        a3: 76,
        a4: 73,
        a5: 75,
        a6: 71,
        a7: 77,
        a8: 74,
        a9: 76,
        a10: 78,
        a11: 73,
        a12: 75,
      },
    },
    {
      id: "s19",
      courseId: "1",
      studentId: "student_19",
      name: "Samuel Hall",
      email: "samuel.h@university.edu",
      grades: {
        a1: 93,
        a2: 91,
        a3: 94,
        a4: 92,
        a5: 93,
        a6: 95,
        a7: 92,
        a8: 94,
        a9: 93,
        a10: 96,
        a11: 91,
        a12: 94,
      },
    },
    {
      id: "s20",
      courseId: "1",
      studentId: "student_20",
      name: "Tina Lopez",
      email: "tina.l@university.edu",
      grades: {
        a1: 79,
        a2: 81,
        a3: 83,
        a4: 80,
        a5: 82,
        a6: 78,
        a7: 84,
        a8: 81,
        a9: 83,
        a10: 85,
        a11: 80,
        a12: 82,
      },
    },
    {
      id: "s21",
      courseId: "1",
      studentId: "student_21",
      name: "Uma Singh",
      email: "uma.s@university.edu",
      grades: {
        a1: 86,
        a2: 88,
        a3: 85,
        a4: 87,
        a5: 89,
        a6: 84,
        a7: 88,
        a8: 86,
        a9: 87,
        a10: 90,
        a11: 85,
        a12: 88,
      },
    },
    {
      id: "s22",
      courseId: "1",
      studentId: "student_22",
      name: "Victor Nguyen",
      email: "victor.n@university.edu",
      grades: {
        a1: 68,
        a2: 70,
        a3: 72,
        a4: 69,
        a5: 71,
        a6: 67,
        a7: 73,
        a8: 70,
        a9: 72,
        a10: 74,
        a11: 69,
        a12: 71,
      },
    },
    {
      id: "s23",
      courseId: "1",
      studentId: "student_23",
      name: "Wendy Clark",
      email: "wendy.c@university.edu",
      grades: {
        a1: 90,
        a2: 92,
        a3: 89,
        a4: 91,
        a5: 93,
        a6: 88,
        a7: 92,
        a8: 90,
        a9: 91,
        a10: 94,
        a11: 89,
        a12: 92,
      },
    },
    {
      id: "s24",
      courseId: "1",
      studentId: "student_24",
      name: "Xavier Torres",
      email: "xavier.t@university.edu",
      grades: {
        a1: 75,
        a2: 77,
        a3: 79,
        a4: 76,
        a5: 78,
        a6: 74,
        a7: 80,
        a8: 77,
        a9: 79,
        a10: 81,
        a11: 76,
        a12: 78,
      },
    },
    {
      id: "s25",
      courseId: "1",
      studentId: "student_25",
      name: "Yara Ahmed",
      email: "yara.a@university.edu",
      grades: {
        a1: 94,
        a2: 96,
        a3: 93,
        a4: 95,
        a5: 97,
        a6: 92,
        a7: 96,
        a8: 94,
        a9: 95,
        a10: 98,
        a11: 93,
        a12: 96,
      },
    },
    {
      id: "s26",
      courseId: "1",
      studentId: "student_26",
      name: "Zachary Moore",
      email: "zachary.m@university.edu",
      grades: {
        a1: 84,
        a2: 86,
        a3: 88,
        a4: 85,
        a5: 87,
        a6: 83,
        a7: 89,
        a8: 86,
        a9: 88,
        a10: 90,
        a11: 85,
        a12: 87,
      },
    },
    {
      id: "s27",
      courseId: "1",
      studentId: "student_27",
      name: "Amy Scott",
      email: "amy.s@university.edu",
      grades: {
        a1: 71,
        a2: 73,
        a3: 75,
        a4: 72,
        a5: 74,
        a6: 70,
        a7: 76,
        a8: 73,
        a9: 75,
        a10: 77,
        a11: 72,
        a12: 74,
      },
    },
    {
      id: "s28",
      courseId: "1",
      studentId: "student_28",
      name: "Brian Foster",
      email: "brian.f@university.edu",
      grades: {
        a1: 88,
        a2: 90,
        a3: 87,
        a4: 89,
        a5: 91,
        a6: 86,
        a7: 90,
        a8: 88,
        a9: 89,
        a10: 92,
        a11: 87,
        a12: 90,
      },
    },
    {
      id: "s29",
      courseId: "1",
      studentId: "student_29",
      name: "Claire Hill",
      email: "claire.h@university.edu",
      grades: {
        a1: 80,
        a2: 82,
        a3: 84,
        a4: 81,
        a5: 83,
        a6: 79,
        a7: 85,
        a8: 82,
        a9: 84,
        a10: 86,
        a11: 81,
        a12: 83,
      },
    },
    {
      id: "s30",
      courseId: "1",
      studentId: "student_30",
      name: "Daniel Reed",
      email: "daniel.r@university.edu",
      grades: {
        a1: 91,
        a2: 93,
        a3: 90,
        a4: 92,
        a5: 94,
        a6: 89,
        a7: 93,
        a8: 91,
        a9: 92,
        a10: 95,
        a11: 90,
        a12: 93,
      },
    },
  ],
  2: [
    {
      id: "s31",
      courseId: "2",
      studentId: "student_31",
      name: "Emily Carter",
      email: "emily.c@university.edu",
      grades: { a13: 88, a14: 92 },
    },
    {
      id: "s32",
      courseId: "2",
      studentId: "student_32",
      name: "Finn O'Brien",
      email: "finn.o@university.edu",
      grades: { a13: 75, a14: 78 },
    },
    {
      id: "s33",
      courseId: "2",
      studentId: "student_33",
      name: "Hannah Lee",
      email: "hannah.l@university.edu",
      grades: { a13: 91, a14: 89 },
    },
    {
      id: "s34",
      courseId: "2",
      studentId: "student_34",
      name: "Isaac Nguyen",
      email: "isaac.n@university.edu",
      grades: { a13: 84, a14: 86 },
    },
    {
      id: "s35",
      courseId: "2",
      studentId: "student_35",
      name: "Jasmine Patel",
      email: "jasmine.p@university.edu",
      grades: { a13: 93, a14: 95 },
    },
    {
      id: "s36",
      courseId: "2",
      studentId: "student_36",
      name: "Kevin Brooks",
      email: "kevin.b@university.edu",
      grades: { a13: 69, a14: 72 },
    },
    {
      id: "s37",
      courseId: "2",
      studentId: "student_37",
      name: "Liam Rodriguez",
      email: "liam.r@university.edu",
      grades: { a13: 87, a14: 90 },
    },
    {
      id: "s38",
      courseId: "2",
      studentId: "student_38",
      name: "Maya Thompson",
      email: "maya.t@university.edu",
      grades: { a13: 94, a14: 91 },
    },
    {
      id: "s39",
      courseId: "2",
      studentId: "student_39",
      name: "Noah Kim",
      email: "noah.k@university.edu",
      grades: { a13: 81, a14: 83 },
    },
    {
      id: "s40",
      courseId: "2",
      studentId: "student_40",
      name: "Olivia Sanchez",
      email: "olivia.s@university.edu",
      grades: { a13: 90, a14: 92 },
    },
    {
      id: "s41",
      courseId: "2",
      studentId: "student_41",
      name: "Peter Wallace",
      email: "peter.w@university.edu",
      grades: { a13: 76, a14: 79 },
    },
    {
      id: "s42",
      courseId: "2",
      studentId: "student_42",
      name: "Quinn Foster",
      email: "quinn.f@university.edu",
      grades: { a13: 88, a14: 85 },
    },
    {
      id: "s43",
      courseId: "2",
      studentId: "student_43",
      name: "Rachel Adams",
      email: "rachel.a@university.edu",
      grades: { a13: 92, a14: 94 },
    },
    {
      id: "s44",
      courseId: "2",
      studentId: "student_44",
      name: "Samuel Ortiz",
      email: "samuel.o@university.edu",
      grades: { a13: 80, a14: 82 },
    },
    {
      id: "s45",
      courseId: "2",
      studentId: "student_45",
      name: "Tara Mitchell",
      email: "tara.m@university.edu",
      grades: { a13: 89, a14: 87 },
    },
    {
      id: "s46",
      courseId: "2",
      studentId: "student_46",
      name: "Umar Khan",
      email: "umar.k@university.edu",
      grades: { a13: 85, a14: 88 },
    },
    {
      id: "s47",
      courseId: "2",
      studentId: "student_47",
      name: "Victoria Perez",
      email: "victoria.p@university.edu",
      grades: { a13: 95, a14: 96 },
    },
    {
      id: "s48",
      courseId: "2",
      studentId: "student_48",
      name: "William Scott",
      email: "william.s@university.edu",
      grades: { a13: 73, a14: 75 },
    },
    {
      id: "s49",
      courseId: "2",
      studentId: "student_49",
      name: "Xavier Coleman",
      email: "xavier.c@university.edu",
      grades: { a13: 82, a14: 84 },
    },
    {
      id: "s50",
      courseId: "2",
      studentId: "student_50",
      name: "Yara Haddad",
      email: "yara.h@university.edu",
      grades: { a13: 90, a14: 89 },
    },
    {
      id: "s51",
      courseId: "2",
      studentId: "student_51",
      name: "Zachary Reed",
      email: "zachary.r@university.edu",
      grades: { a13: 77, a14: 80 },
    },
    {
      id: "s52",
      courseId: "2",
      studentId: "student_52",
      name: "Alyssa Moore",
      email: "alyssa.m@university.edu",
      grades: { a13: 91, a14: 93 },
    },
    {
      id: "s53",
      courseId: "2",
      studentId: "student_53",
      name: "Brandon Lewis",
      email: "brandon.l@university.edu",
      grades: { a13: 68, a14: 70 },
    },
    {
      id: "s54",
      courseId: "2",
      studentId: "student_54",
      name: "Chloe Bennett",
      email: "chloe.b@university.edu",
      grades: { a13: 86, a14: 88 },
    },
    {
      id: "s55",
      courseId: "2",
      studentId: "student_55",
      name: "Daniel Young",
      email: "daniel.y@university.edu",
      grades: { a13: 83, a14: 85 },
    },
  ],

  3: [
    {
      id: "s56",
      courseId: "3",
      studentId: "student_56",
      name: "George Martin",
      email: "george.m@university.edu",
      grades: { a15: 85 },
    },
    {
      id: "s57",
      courseId: "3",
      studentId: "student_57",
      name: "Isabella Wright",
      email: "isabella.w@university.edu",
      grades: { a15: 92 },
    },
    {
      id: "s58",
      courseId: "3",
      studentId: "student_58",
      name: "Jack Turner",
      email: "jack.t@university.edu",
      grades: { a15: 78 },
    },
    {
      id: "s59",
      courseId: "3",
      studentId: "student_59",
      name: "Kylie Roberts",
      email: "kylie.r@university.edu",
      grades: { a15: 88 },
    },
    {
      id: "s60",
      courseId: "3",
      studentId: "student_60",
      name: "Lucas Bennett",
      email: "lucas.b@university.edu",
      grades: { a15: 81 },
    },
    {
      id: "s61",
      courseId: "3",
      studentId: "student_61",
      name: "Megan Flores",
      email: "megan.f@university.edu",
      grades: { a15: 94 },
    },
    {
      id: "s62",
      courseId: "3",
      studentId: "student_62",
      name: "Nathan Price",
      email: "nathan.p@university.edu",
      grades: { a15: 76 },
    },
    {
      id: "s63",
      courseId: "3",
      studentId: "student_63",
      name: "Olga Ivanova",
      email: "olga.i@university.edu",
      grades: { a15: 89 },
    },
    {
      id: "s64",
      courseId: "3",
      studentId: "student_64",
      name: "Paul Simmons",
      email: "paul.s@university.edu",
      grades: { a15: 84 },
    },
    {
      id: "s65",
      courseId: "3",
      studentId: "student_65",
      name: "Renee Walters",
      email: "renee.w@university.edu",
      grades: { a15: 91 },
    },
    {
      id: "s66",
      courseId: "3",
      studentId: "student_66",
      name: "Steven Hall",
      email: "steven.h@university.edu",
      grades: { a15: 79 },
    },
    {
      id: "s67",
      courseId: "3",
      studentId: "student_67",
      name: "Tiffany Brooks",
      email: "tiffany.b@university.edu",
      grades: { a15: 93 },
    },
    {
      id: "s68",
      courseId: "3",
      studentId: "student_68",
      name: "Victor Alvarez",
      email: "victor.a@university.edu",
      grades: { a15: 87 },
    },
    {
      id: "s69",
      courseId: "3",
      studentId: "student_69",
      name: "Wendy Chen",
      email: "wendy.c@university.edu",
      grades: { a15: 90 },
    },
    {
      id: "s70",
      courseId: "3",
      studentId: "student_70",
      name: "Yusuf Malik",
      email: "yusuf.m@university.edu",
      grades: { a15: 82 },
    },
    {
      id: "s71",
      courseId: "3",
      studentId: "student_71",
      name: "Zoe Parker",
      email: "zoe.p@university.edu",
      grades: { a15: 95 },
    },
    {
      id: "s72",
      courseId: "3",
      studentId: "student_72",
      name: "Aaron Phillips",
      email: "aaron.p@university.edu",
      grades: { a15: 77 },
    },
    {
      id: "s73",
      courseId: "3",
      studentId: "student_73",
      name: "Bella Nguyen",
      email: "bella.n@university.edu",
      grades: { a15: 88 },
    },
    {
      id: "s74",
      courseId: "3",
      studentId: "student_74",
      name: "Carlos Rivera",
      email: "carlos.r@university.edu",
      grades: { a15: 83 },
    },
    {
      id: "s75",
      courseId: "3",
      studentId: "student_75",
      name: "Diana Lopez",
      email: "diana.l@university.edu",
      grades: { a15: 91 },
    },
    {
      id: "s76",
      courseId: "3",
      studentId: "student_76",
      name: "Ethan Murphy",
      email: "ethan.m@university.edu",
      grades: { a15: 80 },
    },
    {
      id: "s77",
      courseId: "3",
      studentId: "student_77",
      name: "Fatima Noor",
      email: "fatima.n@university.edu",
      grades: { a15: 94 },
    },
    {
      id: "s78",
      courseId: "3",
      studentId: "student_78",
      name: "Gavin Holt",
      email: "gavin.h@university.edu",
      grades: { a15: 86 },
    },
    {
      id: "s79",
      courseId: "3",
      studentId: "student_79",
      name: "Irene Vasquez",
      email: "irene.v@university.edu",
      grades: { a15: 89 },
    },
    {
      id: "s80",
      courseId: "3",
      studentId: "student_80",
      name: "Jordan Miles",
      email: "jordan.m@university.edu",
      grades: { a15: 84 },
    },
    {
      id: "s81",
      courseId: "3",
      studentId: "student_81",
      name: "Kayla Owens",
      email: "kayla.o@university.edu",
      grades: { a15: 92 },
    },
    {
      id: "s82",
      courseId: "3",
      studentId: "student_82",
      name: "Leo Grant",
      email: "leo.g@university.edu",
      grades: { a15: 78 },
    },
    {
      id: "s83",
      courseId: "3",
      studentId: "student_83",
      name: "Mona Rahman",
      email: "mona.r@university.edu",
      grades: { a15: 90 },
    },
  ],
};

export const MOCK_PRACTICES_BY_COURSE = {
  c1: [
    {
      id: "p1",
      courseId: "c1",
      name: "Chapter 1 Practice Problems",
      publishDate: "2024-01-15",
      publishTime: "00:00",
      dueDate: "2024-01-22",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      allowRetakes: true,
      showSolutions: true,
      attempts: 45,
      completions: 28,
      type: "practice",
    },
    {
      id: "p2",
      courseId: "c1",
      name: "Midterm Review Practice",
      publishDate: "2024-02-01",
      publishTime: "00:00",
      dueDate: "2024-02-15",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      allowRetakes: true,
      showSolutions: true,
      attempts: 67,
      completions: 32,
      type: "practice",
    },
    {
      id: "p3",
      courseId: "c1",
      name: "Data Structures Practice",
      publishDate: "2024-03-01",
      publishTime: "00:00",
      dueDate: "2024-03-08",
      dueTime: "23:59",
      isPublished: false,
      isLocked: false,
      allowRetakes: true,
      showSolutions: true,
      attempts: 0,
      completions: 0,
      type: "practice",
    },
  ],

  c2: [
    {
      id: "p4",
      courseId: "c2",
      name: "Calculus Fundamentals Practice",
      publishDate: "2024-01-20",
      publishTime: "00:00",
      dueDate: "2024-01-27",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      allowRetakes: true,
      showSolutions: true,
      attempts: 52,
      completions: 38,
      type: "practice",
    },
  ],

  c3: [
    {
      id: "p5",
      courseId: "c3",
      name: "Organic Chemistry Practice",
      publishDate: "2024-02-05",
      publishTime: "00:00",
      dueDate: "2024-02-12",
      dueTime: "23:59",
      isPublished: true,
      isLocked: false,
      allowRetakes: true,
      showSolutions: false,
      attempts: 89,
      completions: 45,
      type: "practice",
    },
  ],
};
